name: 'clj-lint-action check'
description: 'Get started with Container actions'
author: 'niyarin'
inputs:
  linters:
    description: 'target linters'
    default: "\"all\""
  sourceroot:
    description: 'directory name of souce directory'
    default: "\"\""
  runner:
      description: ':leiningen or :clojure.'
      default: ":clojure"
  github_token:
    description: 'Github token to report linter results back to check'
    required: true
  base_sha:
      description: 'Github base commit sha of push'
      required: true
  eastwood_linters:
      description: 'Eastwood linters'
      default: '[:bad-arglists :constant-test :def-in-def :deprecations :keyword-typos :local-shadows-var :misplaced-docstrings :no-ns-form-found :redefd-vars :suspicious-expression :suspicious-test :unlimited-use :unused-fn-args :unused-locals :unused-meta-on-macro :unused-namespaces :unused-private-vars :unused-ret-vals :unused-ret-vals-in-try :wrong-arity :wrong-ns-form :wrong-pre-post :wrong-tag]'
runs:
  using: 'docker'
  image: 'docker://xcoo/clj-lint-action:latest'
  args:
    - ${{ inputs.linters }}
    - ${{ inputs.sourceroot }}
    - ${{ inputs.runner }}
    - ${{ inputs.base_sha }}
    - ${{ inputs.eastwood_linters }}
